### ISSUE TITLE
indexing for chapter 8.2

### ISSUE THREAD

**Issue by zhaomingBDAI** [phys-sim-book/mdbook-src#2]
The indexing for some of the symbols seems inconsistent. For example, 

`Now the time integration problem in time step \(n\) becomes finding such optimization path \(x_0, x_1, ..., x_l\) where \(x^l\) locally minimizes the Incremental Potential`

l is being using as both lower index and upper index.

**Comment by liminchen** [comment]
Thank you! I just fixed it.

Best,
Minchen
